import pyautogui

pyautogui.alert('**Atenção**\n'
                ' Clique em [ok] para inicializar o programa.')

#####ENTRA NO MENU INICIAR######
pyautogui.sleep(1)
pyautogui.press('winleft')
pyautogui.sleep(1)
pyautogui.write('C:\ProgramData\Microsoft\Windows\Start Menu')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('right')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.hotkey('Ctrl','f')
pyautogui.sleep(1)
pyautogui.write('inicializar')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.press('space')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)



########### Digita o IP do Servidor ###################

pyautogui.sleep(1)
pyautogui.press('winleft')
pyautogui.sleep(1)
pyautogui.write('\\\\172.16.0.4\chaves')
pyautogui.sleep(1)
pyautogui.press('enter')
########### Realiza a colocação do nome e senha do servidor###########
pyautogui.sleep(6)
pyautogui.write('dto')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.write('2022')
pyautogui.sleep(1)
pyautogui.press(['tab', 'tab'])
pyautogui.sleep(1)
pyautogui.press('enter')

#pyautogui.hotkey('alt','tab')


######### Pesquisa e acessa a pasta PV 59117 ############
pyautogui.sleep(3)
pyautogui.hotkey('ctrl', 'f')
pyautogui.sleep(1)
pyautogui.write('Robo')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.press('space')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
########### Pesquisa e acessa o bloco de notas CHAVES ##########
pyautogui.hotkey('ctrl', 'f')
pyautogui.sleep(1)
pyautogui.write('CHAVES')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.press('space')
pyautogui.alert('**Atenção**\n'
                ' Clique em [ok] para continuar o programa.')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)

######## Copia a Primeira chave e sobe a segunda #############
pyautogui.keyDown('shift')
pyautogui.press('right', presses=29)
pyautogui.keyUp('shift')
pyautogui.hotkey('ctrl', 'c')
pyautogui.sleep(1)
pyautogui.press('backspace')
pyautogui.sleep(1)
pyautogui.press('down')
pyautogui.sleep(1)
pyautogui.press('backspace', presses=2)
pyautogui.sleep(1)

####### Salva o documento CHAVE e realiza o alt tab ############
pyautogui.hotkey('ctrl', 's')
pyautogui.sleep(1)
pyautogui.keyDown('alt')
pyautogui.press('f4')
pyautogui.keyUp('alt')
pyautogui.sleep(1)


###### Pesquisa o documento PV 5555 e acessa o mesmo ##############
pyautogui.hotkey('ctrl', 'f')
pyautogui.sleep(1)
pyautogui.write('FINALIZADOS')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.press('space')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
###### Cola a chave no documento PV 5555 ####
pyautogui.hotkey('ctrl', 'v')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 's')
pyautogui.sleep(1)

###### Abre o wmic e copia o serial ######

pyautogui.press('winleft')
pyautogui.sleep(1)
pyautogui.write('wmic')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.write('bios get serialnumber')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'f')
pyautogui.sleep(1)
pyautogui.write('SerialNumber')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('esc')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl','shift','down','right')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl','c')
pyautogui.sleep(1)

####### Entra no bloco do pv 5555 ############
pyautogui.hotkey('alt','tab')
#pyautogui.keyDown('alt')
#pyautogui.press('tab', presses=2)
#pyautogui.keyUp('alt')
#pyautogui.sleep(1)
#pyautogui.press('enter')
#pyautogui.sleep(1)

#######Realiza os procedimentos de cola do serial######
pyautogui.sleep(1)
pyautogui.press('backspace')
pyautogui.sleep(1)
pyautogui.press('space')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'v')
pyautogui.sleep(1)
pyautogui.press('up')
pyautogui.sleep(1)
pyautogui.press('backspace')
pyautogui.sleep(1)
pyautogui.keyDown('ctrl')
pyautogui.keyDown('shift')
pyautogui.press('left')
pyautogui.keyUp('ctrl')
pyautogui.keyUp('shift')
pyautogui.sleep(1)
pyautogui.press('backspace')
pyautogui.press('up',  presses=2)
pyautogui.sleep(1)
pyautogui.keyDown('shift')
pyautogui.press('left', presses=30)
pyautogui.keyUp('shift')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'c')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 's')
pyautogui.sleep(1)


##### abre o slui ######
pyautogui.press('winleft')
pyautogui.sleep(1)
pyautogui.write('slui')
pyautogui.sleep(1)
pyautogui.press('right')
pyautogui.sleep(1)
pyautogui.press('down')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('enter')


pyautogui.sleep(1)
pyautogui.alert('**Atenção**\n'
                'COLE A CHAVE DO PRODUTO PARA A ATIVAÇÃO!!! '
                       '(ctrl + v) E CLICK EM [AVANÇAR] >>>')


